Fix #92 expand(g:racer_cmd)
racer-rust/vim-racer pull request #93
Opened 2017-06-14 23:32 UTC by Shougo

2017-07-16 14:46 UTC, rhysd commented
Looks good. If no other committer cannot see this, I think @Should should merge this yourself...

2017-07-16 14:58 UTC, rhysd requested changes

2017-07-16 14:58 UTC, rhysd commented on autoload/racer.vim
> +    let s:path = join([
`s:path` doesn't need to be script local. (`s:sep` and `s:pathsep` is also)

2017-07-18 02:39 UTC, Shougo commented on autoload/racer.vim
> +    let s:path = join([
Ah, OK.  I will fix it.

2017-07-19 00:22 UTC, merged

2017-07-19 00:22 UTC, Shougo commented
Merged